name: Scrape Microsoft Customer Stories

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'  # Every Monday at 6am UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Run summary scraper
        run: python scrape_microsoft_stories.py

      - name: Run detail enrichment (first 5 rows only)
        run: |
          python -c "import pandas as pd; df = pd.read_csv('microsoft_customer_stories.csv').head(5); df.to_csv('test_stories.csv', index=False)"
          sed -i 's/microsoft_customer_stories.csv/test_stories.csv/' scrape_story_details.py
          python scrape_story_details.py

      - name: Commit enriched CSV
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add microsoft_customer_stories_enriched.csv
          git commit -m "Update enriched customer stories" || echo "No changes"
          git push
